title: eboshii
description: Thoughts on artificial life, finance, and travel.
baseurl: ""
url: "https://eboshii.github.io"

collections:
  artificial_life:
    output: true
    permalink: /artificial-life/:title/
  quant:
    output: true
    permalink: /quant/:title/
  travel:
    output: true
    permalink: /travel/:title/

defaults:
  - scope:
      path: "_artificial_life"
      type: artificial_life
    values:
      layout: post
  - scope:
      path: "_quant"
      type: quant
    values:
      layout: post
  - scope:
      path: "_travel"
      type: travel
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
